# Jekyll configuration

author: Skyler Ruiter

name: Skyler Ruiter
description: Undergraduate Resercher at GVSU

permalink: /:year/:month/:title/

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']

social:
  github: skyler-ruiter
  stackoverflow: '12929017/skyler-ruiter'
  linkedin: 'skylerruiter'
  instagram: 'skylerruiter'


  